# current directory by default
root_dir: !!str "../generator"

compdb_dir: ../cmake-build

templates: #pathes to template files
  enum: templates/enum.inja
  object: templates/object.inja

input:
  - config.h

output_dir: self_generated