templates: #pathes to template files
  {enum: templates/enum.inja, object: templates/object.inja}}

root_dir: !!str "../generator"

input:
  [&cf config.h, *cf, *cf, *cf]




output_dir: self_generated